[0.056s] Invoking command in '/home/felix/robo/robo_ai_turku_2025/ros2_ws/build/custom_interface': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/felix/robo/robo_ai_turku_2025/ros2_ws/install/lab01_task02:/home/felix/robo/robo_ai_turku_2025/ros2_ws/install/lab01_task01:/home/felix/robo/robo_ai_turku_2025/ros2_ws/install/lab1_bringup:/home/felix/robo/robo_ai_turku_2025/ros2_ws/install/task1:/opt/ros/humble /usr/bin/cmake --build /home/felix/robo/robo_ai_turku_2025/ros2_ws/build/custom_interface -- -j22 -l22
[0.877s] -- Found ament_cmake: 1.3.12 (/opt/ros/humble/share/ament_cmake/cmake)
[0.878s] -- Found rclcpp: 16.0.14 (/opt/ros/humble/share/rclcpp/cmake)
[0.878s] -- Found rosidl_generator_c: 3.1.7 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[0.878s] -- Found rosidl_adapter: 3.1.7 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.878s] -- Found rosidl_generator_cpp: 3.1.7 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[0.878s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.878s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.878s] -- Found rmw_implementation_cmake: 6.1.2 (/opt/ros/humble/share/rmw_implementation_cmake/cmake)
[0.878s] -- Found rmw_fastrtps_cpp: 6.2.8 (/opt/ros/humble/share/rmw_fastrtps_cpp/cmake)
[4.702s] -- Using RMW implementation 'rmw_fastrtps_cpp' as default
[4.759s] -- Found geometry_msgs: 4.9.0 (/opt/ros/humble/share/geometry_msgs/cmake)
[4.772s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[5.000s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[5.000s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[5.001s]   custom_interface --arguments-file
[5.001s]   /home/felix/robo/robo_ai_turku_2025/ros2_ws/build/custom_interface/rosidl_adapter__arguments__custom_interface.json
[5.001s]   --output-dir
[5.001s]   /home/felix/robo/robo_ai_turku_2025/ros2_ws/build/custom_interface/rosidl_adapter/custom_interface
[5.001s]   --output-file
[5.001s]   /home/felix/robo/robo_ai_turku_2025/ros2_ws/build/custom_interface/rosidl_adapter/custom_interface.idls)
[5.001s]   returned error code 1:
[5.001s] 
[5.001s]   Error processing 'double distance' of
[5.001s]   'custom_interface/CalculateDistance_Response': ''double' is an invalid
[5.001s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$''
[5.001s] 
[5.003s]   Traceback (most recent call last):
[5.003s] 
[5.003s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[5.003s]       return _run_code(code, main_globals, None,
[5.003s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[5.003s]       exec(code, run_globals)
[5.003s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[5.003s]       sys.exit(main())
[5.003s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[5.003s]       abs_idl_file = convert_to_idl(
[5.003s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[5.003s]       return convert_srv_to_idl(
[5.003s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[5.003s]       srv = parse_service_string(package_name, input_file.stem, content)
[5.003s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 863, in parse_service_string
[5.003s]       response_message = parse_message_string(
[5.003s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
[5.003s]       Type(type_string, context_package_name=pkg_name),
[5.003s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 277, in __init__
[5.003s]       super(Type, self).__init__(
[5.004s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[5.004s]       raise InvalidResourceName(
[5.004s] 
[5.004s]   rosidl_adapter.parser.InvalidResourceName: 'double' is an invalid message
[5.004s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[5.004s] 
[5.004s] Call Stack (most recent call first):
[5.004s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[5.004s]   CMakeLists.txt:16 (rosidl_generate_interfaces)
[5.004s] 
[5.004s] [0m
[5.004s] -- Configuring incomplete, errors occurred!
[5.004s] See also "/home/felix/robo/robo_ai_turku_2025/ros2_ws/build/custom_interface/CMakeFiles/CMakeOutput.log".
[5.015s] gmake: *** [Makefile:747: cmake_check_build_system] Error 1
[5.021s] Invoked command in '/home/felix/robo/robo_ai_turku_2025/ros2_ws/build/custom_interface' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/felix/robo/robo_ai_turku_2025/ros2_ws/install/lab01_task02:/home/felix/robo/robo_ai_turku_2025/ros2_ws/install/lab01_task01:/home/felix/robo/robo_ai_turku_2025/ros2_ws/install/lab1_bringup:/home/felix/robo/robo_ai_turku_2025/ros2_ws/install/task1:/opt/ros/humble /usr/bin/cmake --build /home/felix/robo/robo_ai_turku_2025/ros2_ws/build/custom_interface -- -j22 -l22
